/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static void delay_int_count(volatile unsigned int nTime)
{
    for(; nTime > 0; nTime--);
}

int main(void)
{
    (*(volatile unsigned *)0x40023830) |= 0x20;
    (*(volatile unsigned *)0x40021400) |= 0x1000;

    delay_int_count(806596);  // about 1 second
    (*(volatile unsigned *)0x40021418) |= 0x40;

    delay_int_count(806596);  // about 1 second
    (*(volatile unsigned *)0x40021418) |= 0x400000;

    /* Loop forever */
	for(;;);
}
